f'''
Plan:
Test serving HTML, CSS, and JS
Test serving images
Test serving audio
Test serving images, text, and audio at once through JSON?
Test serving video
Lay out api endpoints

App functionalities:
    - Log in
    - Manage the API keys associated with your account
    - Manage projects on your account (create, delete, rename, edit)
    - Generate a "segment" from text
    - Generate a script from a specified subject (eg "rainbows")
    - Generate a "sequence" of segments from a script (user-defined or pre-generated)
    - Insert/append new segments in/to a sequence
    - Change the text of a segment
    - Save changed text as a "new version"
    - Regenerate the image, text, or audio in a segment, saving as a new "version" of that element
    - Switch between versions of re/generated images, text, or audio in a segment
    - Export a sequence as a video

Client-->Server side functions:
 - Log in
    - I don't know how logging in works
    - Probably returns some success/fail and userid or sessionid
 - Manage API keys on your account
    - Requires secure database
 - Request new project
    - This is a post request, with the data being the name of the project
    - This will return the project id -> url
 - Request script
    - This is a post request, with the data being the requested subject of the script
    - This will return GPT response
    - The script is stored under the project id in database
        - The script stored in the db will be compiled and updated from client segments any time there is a new generation
 - Request segment from text
    - This is a post request, with the data being the text
    - This will return a segment JSON object {"id": "id", "image_list": ["url"], "text_list": ["text"], "audio_list": ["url"]}
    - The image and audio URLs can be used to request the image and audio
    - The resource URLs will be only whitelisted for that user ID, for privacy
 - Request new segment at index
    - The request body: {"script": "script", "index": int}
    - Returns a segment JSON object
 - Request new version of segment element
    - This is a post request, with a body {"segment_index": int, "text": "text", type: "image|audio|text"}
    - This will return a segment JSON object with the new version added in.
 - Request video export
    - This will render and return a URL to the video
    - The video will be whitelisted to only the user ID
 - 

Server side functions:



TODO later
    - link audio and text versions, since the text directly represents the audio
    - Let the image be generated by a custom prompt
    - Let the client upload custom images (? they can just edit it themselves if they want)
    - pay me  (¬‿¬)っ

'''

# Currently run via
# python -m flask --app server run
from flask import Flask
from markupsafe import escape # for escaping user input

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Help me, World!</p>"
